services:
  - type: web
    name: my-notes-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_notes_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key